# tests/api/api_coverage_manifest.py
"""
Explicit, hand-maintained manifest: every one of the 159 CWM Public API spec
operations, mapped to the concrete `teamstorm` API wrapper method that
implements it.

WHY A MANIFEST INSTEAD OF A PARSER
-----------------------------------
An earlier automated pass tried to prove coverage by regexing `teamstorm/api/*.py`
for literal `self.client.<verb>("...")` call strings and comparing the paths
found against swagger.json. That approach reported 27 false "missing"
operations, because it cannot see paths built any other way than a literal
string argument:

- `teamstorm/api/attachments.py` builds every path through
  `_AttachmentsAPIBase._attachments_path()` plus string formatting on the
  *result* of that helper (e.g. `f"{self._attachments_path(...)}/{version}"`)
  -- 18 operations (WorkitemAttachments + DocumentAttachments) invisible to a
  scanner that only understands `client.get("literal/path")`.
- `teamstorm/api/sharing.py` assigns the path to a local `path` variable before
  passing it to `_list_shared_permissions`/`_create_shared_permission`/etc.
  -- 8 operations (WorkitemsSharing + DocumentsSharing) invisible for the
  same reason.
- `teamstorm/api/workitems.py`'s `update_attribute` (the WorkitemAttributes PUT)
  also builds `path = f"..."` first, then calls `self.client.put(path, ...)`
  -- 1 more operation.

All 27 of those ARE implemented (verified by reading the source directly,
tracing every helper call to its base implementation) -- the scanner's
failure was in the scanner, not the wrapper. Per the project's standing
guidance ("an explicit, correct manifest beats a clever, flaky parser"),
this file replaces that approach entirely: every row below was produced by
reading the actual `teamstorm/api/*.py` source for the method it names, not by
pattern-matching strings.

WHAT THIS FILE PROVES vs. WHAT OTHER TESTS PROVE
--------------------------------------------------
`tests/api/test_api_coverage.py` uses this manifest for two checks:
1. The manifest's (http_method, path) set is EXACTLY the spec's operation
   set -- no operation is missing, and no phantom row lacks a real spec
   operation to back it (both directions asserted).
2. Every manifest row's (api_property, api_method) resolves to a real,
   callable method on the object `TeamStormAPI.<api_property>` returns.

That proves *exhaustiveness*: every spec operation has a named, existing
wrapper method. It does NOT re-verify that a given method's internal f-string
actually produces the exact path string -- that per-method verb/path/body
assertion is what the per-resource tests under `tests/api/test_api_*.py`
already do (see docs/api-analysis/conventions.md section 8). The two kinds
of test are complementary: this file proves breadth (all 159 covered,
nothing double-counted or invented), the per-resource tests prove
correctness (the one method for each operation calls the right
verb/path/params).

MAINTENANCE
-----------
Path segments are the spec's own placeholder names (e.g. "{workspace}",
"{workitem}") with the common "/cwm/public/api/v1" prefix stripped -- that
prefix is added by `TsClient` itself (`teamstorm.client.API_PREFIX`), so every
`teamstorm/api/*.py` module's f-strings never include it either. If a future task
adds or removes a spec operation, update this manifest and
docs/api-coverage.md together; `tests/api/test_api_coverage.py` will fail
loudly on any drift between this file and a present `swagger.json`.
"""

from __future__ import annotations

from typing import List, NamedTuple


class OpMapping(NamedTuple):
    http_method: str
    path: str
    tag: str
    operation_id: str
    api_property: str
    api_class: str
    api_method: str


COVERAGE_MANIFEST: List[OpMapping] = [
    # --- Agile (4) ---------------------------------------------------------
    OpMapping("POST", "/workspaces/{workspace}/agile", "Agile", "CreateAgile", "agile", "AgileAPI", "create"),
    OpMapping("GET", "/workspaces/{workspace}/agile/list", "Agile", "GetAgileExtensions", "agile", "AgileAPI", "list"),
    OpMapping(
        "DELETE", "/workspaces/{workspace}/agile/{agileId}", "Agile", "DeleteAgile", "agile", "AgileAPI", "delete"
    ),
    OpMapping("GET", "/workspaces/{workspace}/agile/{agileId}", "Agile", "GetAgile", "agile", "AgileAPI", "get"),
    # --- Attributes (8) -----------------------------------------------------
    OpMapping(
        "GET",
        "/workspaces/{workspace}/attributes",
        "Attributes",
        "ListAttributes",
        "attributes",
        "AttributesAPI",
        "list",
    ),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/attributes",
        "Attributes",
        "CreateAttribute",
        "attributes",
        "AttributesAPI",
        "create",
    ),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/attributes/{attributeId}",
        "Attributes",
        "DeleteAttribute",
        "attributes",
        "AttributesAPI",
        "delete",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/attributes/{attributeId}",
        "Attributes",
        "GetAttribute",
        "attributes",
        "AttributesAPI",
        "get",
    ),
    OpMapping(
        "PATCH",
        "/workspaces/{workspace}/attributes/{attributeId}",
        "Attributes",
        "PatchAttribute",
        "attributes",
        "AttributesAPI",
        "patch",
    ),
    OpMapping(
        "PATCH",
        "/workspaces/{workspace}/attributes/{attributeId}/options",
        "Attributes",
        "PatchAttributeOption",
        "attributes",
        "AttributesAPI",
        "patch_option",
    ),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/attributes/{attributeId}/options",
        "Attributes",
        "AddAttributeOption",
        "attributes",
        "AttributesAPI",
        "add_option",
    ),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/attributes/{attributeId}/options/{optionId}",
        "Attributes",
        "DeleteAttributeOption",
        "attributes",
        "AttributesAPI",
        "delete_option",
    ),
    # --- DocumentAttachments (9) --------------------------------------------
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/documents/{document}/attachments",
        "DocumentAttachments",
        "DeleteDocumentAttachments",
        "document_attachments",
        "DocumentAttachmentsAPI",
        "delete_all",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/documents/{document}/attachments",
        "DocumentAttachments",
        "GetDocumentAttachments",
        "document_attachments",
        "DocumentAttachmentsAPI",
        "list",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/documents/{document}/attachments/versions",
        "DocumentAttachments",
        "GetDocumentAttachmentsWithVersions",
        "document_attachments",
        "DocumentAttachmentsAPI",
        "list_versions",
    ),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/documents/{document}/attachments/{attachmentId}",
        "DocumentAttachments",
        "DeleteDocumentAttachment",
        "document_attachments",
        "DocumentAttachmentsAPI",
        "delete",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/documents/{document}/attachments/{attachmentId}",
        "DocumentAttachments",
        "GetDocumentAttachment",
        "document_attachments",
        "DocumentAttachmentsAPI",
        "get",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/documents/{document}/attachments/{attachmentId}/download",
        "DocumentAttachments",
        "DownloadDocumentAttachments",
        "document_attachments",
        "DocumentAttachmentsAPI",
        "download",
    ),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/documents/{document}/attachments/{attachmentId}/upload",
        "DocumentAttachments",
        "UploadDocumentAttachments",
        "document_attachments",
        "DocumentAttachmentsAPI",
        "upload",
    ),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/documents/{document}/attachments/{attachmentId}/versions/{attachmentVersion}",
        "DocumentAttachments",
        "DeleteDocumentAttachmentVersion",
        "document_attachments",
        "DocumentAttachmentsAPI",
        "delete_version",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/documents/{document}/attachments/{attachmentId}/versions/{attachmentVersion}",
        "DocumentAttachments",
        "GetDocumentAttachmentWithVersions",
        "document_attachments",
        "DocumentAttachmentsAPI",
        "get_version",
    ),
    # --- DocumentComments (3) ------------------------------------------------
    OpMapping(
        "GET",
        "/workspaces/{workspace}/documents/{document}/comments",
        "DocumentComments",
        "ListDocumentComments",
        "document_comments",
        "DocumentCommentsAPI",
        "list",
    ),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/documents/{document}/comments",
        "DocumentComments",
        "CreateDocumentComment",
        "document_comments",
        "DocumentCommentsAPI",
        "create",
    ),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/documents/{document}/comments/{commentId}",
        "DocumentComments",
        "DeleteDocumentComment",
        "document_comments",
        "DocumentCommentsAPI",
        "delete",
    ),
    # --- DocumentLinks (4) ----------------------------------------------------
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/documents/{document}/workitem-links",
        "DocumentLinks",
        "DeleteDocumentWorkitemLink",
        "document_workitem_links",
        "DocumentWorkitemLinksAPI",
        "delete",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/documents/{document}/workitem-links",
        "DocumentLinks",
        "GetDocumentWorkitemLinks",
        "document_workitem_links",
        "DocumentWorkitemLinksAPI",
        "list",
    ),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/documents/{document}/workitem-links",
        "DocumentLinks",
        "CreateDocumentWorkitemLink",
        "document_workitem_links",
        "DocumentWorkitemLinksAPI",
        "create",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/workitems/{workitem}/document-links",
        "DocumentLinks",
        "GetWorkitemDocumentLinks",
        "document_workitem_links",
        "DocumentWorkitemLinksAPI",
        "list_by_workitem",
    ),
    # --- DocumentVersions (3) --------------------------------------------------
    OpMapping(
        "GET",
        "/workspaces/{workspace}/documents/{document}/versions",
        "DocumentVersions",
        "ListDocumentVersions",
        "document_versions",
        "DocumentVersionsAPI",
        "list",
    ),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/documents/{document}/versions/{documentVersion}",
        "DocumentVersions",
        "DeleteDocumentVersion",
        "document_versions",
        "DocumentVersionsAPI",
        "delete",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/documents/{document}/versions/{documentVersion}",
        "DocumentVersions",
        "GetDocumentByVersion",
        "document_versions",
        "DocumentVersionsAPI",
        "get",
    ),
    # --- Documents (7) -----------------------------------------------------
    OpMapping(
        "GET", "/workspaces/{workspace}/documents", "Documents", "ListDocuments", "documents", "DocumentsAPI", "list"
    ),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/documents",
        "Documents",
        "CreateDocument",
        "documents",
        "DocumentsAPI",
        "create",
    ),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/documents/{document}",
        "Documents",
        "DeleteDocument",
        "documents",
        "DocumentsAPI",
        "delete",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/documents/{document}",
        "Documents",
        "GetDocument",
        "documents",
        "DocumentsAPI",
        "get",
    ),
    OpMapping(
        "PATCH",
        "/workspaces/{workspace}/documents/{document}",
        "Documents",
        "PatchDocument",
        "documents",
        "DocumentsAPI",
        "patch",
    ),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/documents/{document}/block",
        "Documents",
        "BlockDocument",
        "documents",
        "DocumentsAPI",
        "block",
    ),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/documents/{document}/unblock",
        "Documents",
        "UnblockDocument",
        "documents",
        "DocumentsAPI",
        "unblock",
    ),
    # --- DocumentsSharing (4) --------------------------------------------------
    OpMapping(
        "GET",
        "/workspaces/{workspace}/documents/{document}/sharing",
        "DocumentsSharing",
        "ListSharedDocumentPermissions",
        "document_sharing",
        "DocumentSharingAPI",
        "list",
    ),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/documents/{document}/sharing",
        "DocumentsSharing",
        "CreateSharedDocumentPermission",
        "document_sharing",
        "DocumentSharingAPI",
        "create",
    ),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/documents/{document}/sharing/{permissionId}",
        "DocumentsSharing",
        "DeleteSharedDocumentPermission",
        "document_sharing",
        "DocumentSharingAPI",
        "delete",
    ),
    OpMapping(
        "PATCH",
        "/workspaces/{workspace}/documents/{document}/sharing/{permissionId}",
        "DocumentsSharing",
        "PatchSharedDocumentPermission",
        "document_sharing",
        "DocumentSharingAPI",
        "patch",
    ),
    # --- DocumentsStatuses (2) -------------------------------------------------
    OpMapping(
        "GET",
        "/workspaces/{workspace}/documents-statuses",
        "DocumentsStatuses",
        "ListDocumentStatuses",
        "document_statuses",
        "DocumentStatusesAPI",
        "list",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/documents-statuses/{status}",
        "DocumentsStatuses",
        "GetDocumentsStatus",
        "document_statuses",
        "DocumentStatusesAPI",
        "get",
    ),
    # --- Folders (5) ---------------------------------------------------------
    OpMapping("GET", "/workspaces/{workspace}/folders", "Folders", "ListFolders", "folders", "FoldersAPI", "list"),
    OpMapping("POST", "/workspaces/{workspace}/folders", "Folders", "CreateFolder", "folders", "FoldersAPI", "create"),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/folders/{folderId}",
        "Folders",
        "DeleteFolder",
        "folders",
        "FoldersAPI",
        "delete",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/folders/{folderId}",
        "Folders",
        "GetFolder",
        "folders",
        "FoldersAPI",
        "get",
    ),
    OpMapping(
        "PATCH",
        "/workspaces/{workspace}/folders/{folderId}",
        "Folders",
        "PatchFolder",
        "folders",
        "FoldersAPI",
        "patch",
    ),
    # --- GitIntegrationTokens (6) ------------------------------------------
    OpMapping(
        "GET",
        "/workspaces/{workspace}/git-integration-tokens",
        "GitIntegrationTokens",
        "ListTokens",
        "git_integration_tokens",
        "GitIntegrationTokensAPI",
        "list",
    ),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/git-integration-tokens",
        "GitIntegrationTokens",
        "CreateToken",
        "git_integration_tokens",
        "GitIntegrationTokensAPI",
        "create",
    ),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/git-integration-tokens/{tokenId}",
        "GitIntegrationTokens",
        "DeleteTokenAsync",
        "git_integration_tokens",
        "GitIntegrationTokensAPI",
        "delete",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/git-integration-tokens/{tokenId}",
        "GitIntegrationTokens",
        "GetToken",
        "git_integration_tokens",
        "GitIntegrationTokensAPI",
        "get",
    ),
    OpMapping(
        "PUT",
        "/workspaces/{workspace}/git-integration-tokens/{tokenId}",
        "GitIntegrationTokens",
        "UpdateToken",
        "git_integration_tokens",
        "GitIntegrationTokensAPI",
        "update",
    ),
    OpMapping(
        "PUT",
        "/workspaces/{workspace}/git-integration-tokens/{tokenId}/refresh",
        "GitIntegrationTokens",
        "RefreshToken",
        "git_integration_tokens",
        "GitIntegrationTokensAPI",
        "refresh",
    ),
    # --- LinkTypes (1) -------------------------------------------------------
    OpMapping(
        "GET",
        "/workspaces/{workspace}/link-types",
        "LinkTypes",
        "ListLinkTypes",
        "links",
        "LinksAPI",
        "list_types",
    ),
    # --- OpenId (4) ----------------------------------------------------------
    OpMapping("GET", "/open-id/connections", "OpenId", "GetConnections", "open_id", "OpenIdAPI", "list"),
    OpMapping("POST", "/open-id/connections", "OpenId", "CreateConnection", "open_id", "OpenIdAPI", "create"),
    OpMapping(
        "DELETE",
        "/open-id/connections/{connectionId}",
        "OpenId",
        "DeleteConnection",
        "open_id",
        "OpenIdAPI",
        "delete",
    ),
    OpMapping(
        "POST",
        "/open-id/connections/{connectionId}/users",
        "OpenId",
        "CreateUser",
        "open_id",
        "OpenIdAPI",
        "create_user",
    ),
    # --- PortfolioElements (7) -----------------------------------------------
    OpMapping(
        "GET",
        "/workspaces/{workspace}/portfolio-elements",
        "PortfolioElements",
        "ListPortfolioElements",
        "portfolio_elements",
        "PortfolioElementsAPI",
        "list",
    ),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/portfolio-elements",
        "PortfolioElements",
        "",
        "portfolio_elements",
        "PortfolioElementsAPI",
        "create",
    ),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/portfolio-elements/{portfolioElementId}",
        "PortfolioElements",
        "",
        "portfolio_elements",
        "PortfolioElementsAPI",
        "delete",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/portfolio-elements/{portfolioElementId}",
        "PortfolioElements",
        "GetPortfolioElement",
        "portfolio_elements",
        "PortfolioElementsAPI",
        "get",
    ),
    OpMapping(
        "PATCH",
        "/workspaces/{workspace}/portfolio-elements/{portfolioElementId}",
        "PortfolioElements",
        "",
        "portfolio_elements",
        "PortfolioElementsAPI",
        "patch",
    ),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/portfolio-elements/{portfolioElementId}/workitems/{workitem}",
        "PortfolioElements",
        "",
        "portfolio_elements",
        "PortfolioElementsAPI",
        "unlink_workitem",
    ),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/portfolio-elements/{portfolioElementId}/workitems/{workitem}",
        "PortfolioElements",
        "",
        "portfolio_elements",
        "PortfolioElementsAPI",
        "link_workitem",
    ),
    # --- Portfolios (5) --------------------------------------------------------
    OpMapping(
        "GET",
        "/workspaces/{workspace}/portfolios",
        "Portfolios",
        "ListPortfolios",
        "portfolios",
        "PortfoliosAPI",
        "list",
    ),
    OpMapping("POST", "/workspaces/{workspace}/portfolios", "Portfolios", "", "portfolios", "PortfoliosAPI", "create"),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/portfolios/{portfolioId}",
        "Portfolios",
        "",
        "portfolios",
        "PortfoliosAPI",
        "delete",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/portfolios/{portfolioId}",
        "Portfolios",
        "GetPortfolio",
        "portfolios",
        "PortfoliosAPI",
        "get",
    ),
    OpMapping(
        "PATCH",
        "/workspaces/{workspace}/portfolios/{portfolioId}",
        "Portfolios",
        "",
        "portfolios",
        "PortfoliosAPI",
        "patch",
    ),
    # --- Providers (1) -----------------------------------------------------
    OpMapping("GET", "/providers", "Providers", "GetProviders", "providers", "ProvidersAPI", "list"),
    # --- Queries (3) ---------------------------------------------------------
    OpMapping(
        "GET",
        "/queries/{queryId}/workitems",
        "Queries",
        "ListQueryWorkitems",
        "queries",
        "QueriesAPI",
        "list_workitems",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/queries/{queryId}/visibility",
        "Queries",
        "GetQueryVisibilitySettings",
        "queries",
        "QueriesAPI",
        "get_visibility",
    ),
    OpMapping(
        "PUT",
        "/workspaces/{workspace}/queries/{queryId}/visibility",
        "Queries",
        "UpdateQueryVisibilitySettings",
        "queries",
        "QueriesAPI",
        "update_visibility",
    ),
    # --- Roles (5) -------------------------------------------------------------
    OpMapping("GET", "/workspaces/{workspace}/roles", "Roles", "ListRoles", "roles", "RolesAPI", "list"),
    OpMapping("POST", "/workspaces/{workspace}/roles", "Roles", "CreateRole", "roles", "RolesAPI", "create"),
    OpMapping("DELETE", "/workspaces/{workspace}/roles/{roleId}", "Roles", "DeleteRole", "roles", "RolesAPI", "delete"),
    OpMapping("GET", "/workspaces/{workspace}/roles/{roleId}", "Roles", "GetRole", "roles", "RolesAPI", "get"),
    OpMapping("PATCH", "/workspaces/{workspace}/roles/{roleId}", "Roles", "PatchRole", "roles", "RolesAPI", "patch"),
    # --- Sprints (5) -----------------------------------------------------------
    OpMapping("GET", "/workspaces/{workspace}/sprints", "Sprints", "ListSprints", "sprints", "SprintsAPI", "list"),
    OpMapping("POST", "/workspaces/{workspace}/sprints", "Sprints", "CreateSprint", "sprints", "SprintsAPI", "create"),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/sprints/{sprintId}",
        "Sprints",
        "DeleteSprint",
        "sprints",
        "SprintsAPI",
        "delete",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/sprints/{sprintId}",
        "Sprints",
        "GetSprint",
        "sprints",
        "SprintsAPI",
        "get",
    ),
    OpMapping(
        "PATCH",
        "/workspaces/{workspace}/sprints/{sprintId}",
        "Sprints",
        "PatchSprint",
        "sprints",
        "SprintsAPI",
        "patch",
    ),
    # --- StatusCategories (1) ----------------------------------------------
    OpMapping(
        "GET",
        "/status-categories",
        "StatusCategories",
        "ListStatusCategories",
        "statuses",
        "StatusesAPI",
        "list_categories",
    ),
    # --- Statuses (3) --------------------------------------------------------
    OpMapping("GET", "/workspaces/{workspace}/statuses", "Statuses", "ListStatuses", "statuses", "StatusesAPI", "list"),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/statuses",
        "Statuses",
        "CreateStatus",
        "statuses",
        "StatusesAPI",
        "create",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/statuses/{status}",
        "Statuses",
        "GetStatus",
        "statuses",
        "StatusesAPI",
        "get",
    ),
    # --- TimeTracking (2) ------------------------------------------------------
    OpMapping(
        "GET",
        "/workspaces/time-tracking-entries",
        "TimeTracking",
        "GetTimeTrackingEntries",
        "time_tracking",
        "TimeTrackingAPI",
        "list",
    ),
    OpMapping(
        "GET",
        "/workspaces/time-tracking-entries/updates",
        "TimeTracking",
        "GetTimeTrackingEntriesUpdates",
        "time_tracking",
        "TimeTrackingAPI",
        "list_updates",
    ),
    # --- Types (7) -------------------------------------------------------------
    OpMapping("GET", "/workspaces/{workspace}/types", "Types", "ListTypes", "types", "TypesAPI", "list"),
    OpMapping("POST", "/workspaces/{workspace}/types", "Types", "CreateType", "types", "TypesAPI", "create"),
    OpMapping("DELETE", "/workspaces/{workspace}/types/{type}", "Types", "DeleteType", "types", "TypesAPI", "delete"),
    OpMapping("GET", "/workspaces/{workspace}/types/{type}", "Types", "GetType", "types", "TypesAPI", "get"),
    OpMapping("PATCH", "/workspaces/{workspace}/types/{type}", "Types", "PatchType", "types", "TypesAPI", "patch"),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/types/{type}/attributes/{attributeId}",
        "Types",
        "DeleteTypeAttribute",
        "types",
        "TypesAPI",
        "remove_attribute",
    ),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/types/{type}/attributes/{attributeId}",
        "Types",
        "AddTypeAttribute",
        "types",
        "TypesAPI",
        "add_attribute",
    ),
    # --- UserGroups (2) ----------------------------------------------------
    OpMapping("GET", "/user-groups", "UserGroups", "ListUserGroups", "groups", "GroupsAPI", "list"),
    OpMapping("GET", "/user-groups/{group}", "UserGroups", "GetUserGroup", "groups", "GroupsAPI", "get"),
    # --- Users (4) -------------------------------------------------------------
    OpMapping("GET", "/users", "Users", "ListUsers", "users", "UsersAPI", "list"),
    OpMapping("POST", "/users/block/{userId}", "Users", "BlockUser", "users", "UsersAPI", "block"),
    OpMapping("POST", "/users/unblock/{userId}", "Users", "UnblockUser", "users", "UsersAPI", "unblock"),
    OpMapping("GET", "/users/{user}", "Users", "GetUser", "users", "UsersAPI", "get"),
    # --- Workflows (5) -----------------------------------------------------
    OpMapping(
        "GET",
        "/workspaces/{workspace}/workflows",
        "Workflows",
        "ListWorkflows",
        "workflows",
        "WorkflowsAPI",
        "list",
    ),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/workflows",
        "Workflows",
        "CreateWorkflow",
        "workflows",
        "WorkflowsAPI",
        "create",
    ),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/workflows/{workflow}",
        "Workflows",
        "DeleteWorkflow",
        "workflows",
        "WorkflowsAPI",
        "delete",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/workflows/{workflow}",
        "Workflows",
        "GetWorkflow",
        "workflows",
        "WorkflowsAPI",
        "get",
    ),
    OpMapping(
        "PATCH",
        "/workspaces/{workspace}/workflows/{workflow}",
        "Workflows",
        "PatchWorkflow",
        "workflows",
        "WorkflowsAPI",
        "patch",
    ),
    # --- WorkitemAttachments (9) ---------------------------------------------
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/workitems/{workitem}/attachments",
        "WorkitemAttachments",
        "DeleteWorkitemAttachments",
        "workitem_attachments",
        "WorkitemAttachmentsAPI",
        "delete_all",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/workitems/{workitem}/attachments",
        "WorkitemAttachments",
        "GetWorkitemAttachments",
        "workitem_attachments",
        "WorkitemAttachmentsAPI",
        "list",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/workitems/{workitem}/attachments/versions",
        "WorkitemAttachments",
        "GetWorkitemAttachmentsWithVersions",
        "workitem_attachments",
        "WorkitemAttachmentsAPI",
        "list_versions",
    ),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/workitems/{workitem}/attachments/{attachmentId}",
        "WorkitemAttachments",
        "DeleteWorkitemAttachment",
        "workitem_attachments",
        "WorkitemAttachmentsAPI",
        "delete",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/workitems/{workitem}/attachments/{attachmentId}",
        "WorkitemAttachments",
        "GetWorkitemAttachment",
        "workitem_attachments",
        "WorkitemAttachmentsAPI",
        "get",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/workitems/{workitem}/attachments/{attachmentId}/download",
        "WorkitemAttachments",
        "DownloadWorkitemAttachments",
        "workitem_attachments",
        "WorkitemAttachmentsAPI",
        "download",
    ),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/workitems/{workitem}/attachments/{attachmentId}/upload",
        "WorkitemAttachments",
        "UploadWorkitemAttachments",
        "workitem_attachments",
        "WorkitemAttachmentsAPI",
        "upload",
    ),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/workitems/{workitem}/attachments/{attachmentId}/versions/{attachmentVersion}",
        "WorkitemAttachments",
        "DeleteWorkitemAttachmentVersion",
        "workitem_attachments",
        "WorkitemAttachmentsAPI",
        "delete_version",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/workitems/{workitem}/attachments/{attachmentId}/versions/{attachmentVersion}",
        "WorkitemAttachments",
        "GetWorkitemAttachmentWithVersions",
        "workitem_attachments",
        "WorkitemAttachmentsAPI",
        "get_version",
    ),
    # --- WorkitemAttributes (2) ---------------------------------------------
    OpMapping(
        "GET",
        "/workspaces/{workspace}/workitems/{workitem}/attributes",
        "WorkitemAttributes",
        "ListWorkitemAttributes",
        "workitems",
        "WorkitemsAPI",
        "list_attributes",
    ),
    OpMapping(
        "PUT",
        "/workspaces/{workspace}/workitems/{workitem}/attributes/{attributeId}",
        "WorkitemAttributes",
        "UpdateWorkitemAttribute",
        "workitems",
        "WorkitemsAPI",
        "update_attribute",
    ),
    # --- WorkitemComments (6) ------------------------------------------------
    OpMapping(
        "GET",
        "/workspaces/{workspace}/workitems/{workitem}/comments",
        "WorkitemComments",
        "ListWorkitemComments",
        "workitem_comments",
        "WorkitemCommentsAPI",
        "list",
    ),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/workitems/{workitem}/comments",
        "WorkitemComments",
        "CreateWorkitemComment",
        "workitem_comments",
        "WorkitemCommentsAPI",
        "create",
    ),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/workitems/{workitem}/comments/{commentId}",
        "WorkitemComments",
        "DeleteWorkitemComment",
        "workitem_comments",
        "WorkitemCommentsAPI",
        "delete",
    ),
    OpMapping(
        "PUT",
        "/workspaces/{workspace}/workitems/{workitem}/comments/{commentId}",
        "WorkitemComments",
        "UpdateWorkitemComment",
        "workitem_comments",
        "WorkitemCommentsAPI",
        "update",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/workitems/{workitem}/comments/{commentId}/visibility",
        "WorkitemComments",
        "GetWorkitemCommentVisibilitySettings",
        "workitem_comments",
        "WorkitemCommentsAPI",
        "get_visibility",
    ),
    OpMapping(
        "PUT",
        "/workspaces/{workspace}/workitems/{workitem}/comments/{commentId}/visibility",
        "WorkitemComments",
        "UpdateWorkitemCommentVisibilitySettings",
        "workitem_comments",
        "WorkitemCommentsAPI",
        "update_visibility",
    ),
    # --- WorkitemLinks (3) -------------------------------------------------
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/links/{linkId}",
        "WorkitemLinks",
        "DeleteWorkitemLink",
        "links",
        "LinksAPI",
        "delete",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/workitems/{workitem}/links",
        "WorkitemLinks",
        "ListWorkitemLinks",
        "links",
        "LinksAPI",
        "list",
    ),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/workitems/{workitem}/links",
        "WorkitemLinks",
        "CreateWorkitemLink",
        "links",
        "LinksAPI",
        "create",
    ),
    # --- Workitems (8) -----------------------------------------------------
    OpMapping(
        "GET", "/workspaces/{workspace}/workitems", "Workitems", "ListWorkitems", "workitems", "WorkitemsAPI", "list"
    ),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/workitems",
        "Workitems",
        "CreateWorkitem",
        "workitems",
        "WorkitemsAPI",
        "create",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/workitems/by-parent/{parent}",
        "Workitems",
        "ListWorkitemsByParent",
        "workitems",
        "WorkitemsAPI",
        "list_by_parent",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/workitems/count",
        "Workitems",
        "GetWorkitemsCount",
        "workitems",
        "WorkitemsAPI",
        "count",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/workitems/updates",
        "Workitems",
        "ListWorkitemsUpdates",
        "workitems",
        "WorkitemsAPI",
        "list_updates",
    ),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/workitems/{workitem}",
        "Workitems",
        "DeleteWorkitem",
        "workitems",
        "WorkitemsAPI",
        "delete",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/workitems/{workitem}",
        "Workitems",
        "GetWorkitemById",
        "workitems",
        "WorkitemsAPI",
        "get",
    ),
    OpMapping(
        "PATCH",
        "/workspaces/{workspace}/workitems/{workitem}",
        "Workitems",
        "PatchWorkitem",
        "workitems",
        "WorkitemsAPI",
        "patch",
    ),
    # --- WorkitemsSharing (4) ------------------------------------------------
    OpMapping(
        "GET",
        "/workspaces/{workspace}/workitems/{workitem}/sharing",
        "WorkitemsSharing",
        "ListSharedWorkitemPermissions",
        "workitem_sharing",
        "WorkitemSharingAPI",
        "list",
    ),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/workitems/{workitem}/sharing",
        "WorkitemsSharing",
        "CreateSharedWorkitemPermission",
        "workitem_sharing",
        "WorkitemSharingAPI",
        "create",
    ),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/workitems/{workitem}/sharing/{permissionId}",
        "WorkitemsSharing",
        "DeleteSharedWorkitemPermission",
        "workitem_sharing",
        "WorkitemSharingAPI",
        "delete",
    ),
    OpMapping(
        "PATCH",
        "/workspaces/{workspace}/workitems/{workitem}/sharing/{permissionId}",
        "WorkitemsSharing",
        "PatchSharedWorkitemPermission",
        "workitem_sharing",
        "WorkitemSharingAPI",
        "patch",
    ),
    # --- WorkspaceGroups (6) -------------------------------------------------
    OpMapping(
        "GET",
        "/workspaces/{workspace}/groups",
        "WorkspaceGroups",
        "FilterWorkspaceUsers",
        "workspace_groups",
        "WorkspaceGroupsAPI",
        "list",
    ),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/groups/{groupId}",
        "WorkspaceGroups",
        "RemoveWorkspaceGroup",
        "workspace_groups",
        "WorkspaceGroupsAPI",
        "remove",
    ),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/groups/{groupId}",
        "WorkspaceGroups",
        "AddWorkspaceGroup",
        "workspace_groups",
        "WorkspaceGroupsAPI",
        "add",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/groups/{groupId}/roles",
        "WorkspaceGroups",
        "GetGroupRoles",
        "workspace_groups",
        "WorkspaceGroupsAPI",
        "get_roles",
    ),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/groups/{groupId}/roles/{roleId}",
        "WorkspaceGroups",
        "RemoveRoleForGroup",
        "workspace_groups",
        "WorkspaceGroupsAPI",
        "remove_role",
    ),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/groups/{groupId}/roles/{roleId}",
        "WorkspaceGroups",
        "AddGroupRole",
        "workspace_groups",
        "WorkspaceGroupsAPI",
        "add_role",
    ),
    # --- WorkspaceUsers (6) --------------------------------------------------
    OpMapping(
        "GET",
        "/workspaces/{workspace}/users",
        "WorkspaceUsers",
        "GetWorkspaceUsers",
        "workspace_users",
        "WorkspaceUsersAPI",
        "list",
    ),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/users/{userId}",
        "WorkspaceUsers",
        "RemoveWorkspaceUser",
        "workspace_users",
        "WorkspaceUsersAPI",
        "remove",
    ),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/users/{userId}",
        "WorkspaceUsers",
        "AddWorkspaceUser",
        "workspace_users",
        "WorkspaceUsersAPI",
        "add",
    ),
    OpMapping(
        "GET",
        "/workspaces/{workspace}/users/{userId}/roles",
        "WorkspaceUsers",
        "GetUserRoles",
        "workspace_users",
        "WorkspaceUsersAPI",
        "get_roles",
    ),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}/users/{userId}/roles/{roleId}",
        "WorkspaceUsers",
        "RemoveRoleForUser",
        "workspace_users",
        "WorkspaceUsersAPI",
        "remove_role",
    ),
    OpMapping(
        "POST",
        "/workspaces/{workspace}/users/{userId}/roles/{roleId}",
        "WorkspaceUsers",
        "AddUserRole",
        "workspace_users",
        "WorkspaceUsersAPI",
        "add_role",
    ),
    # --- Workspaces (5) ----------------------------------------------------
    OpMapping("GET", "/workspaces", "Workspaces", "ListWorkspaces", "workspaces", "WorkspacesAPI", "list"),
    OpMapping("POST", "/workspaces", "Workspaces", "CreateWorkspace", "workspaces", "WorkspacesAPI", "create"),
    OpMapping(
        "DELETE",
        "/workspaces/{workspace}",
        "Workspaces",
        "DeleteWorkspace",
        "workspaces",
        "WorkspacesAPI",
        "delete",
    ),
    OpMapping("GET", "/workspaces/{workspace}", "Workspaces", "GetWorkspace", "workspaces", "WorkspacesAPI", "get"),
    OpMapping(
        "PATCH",
        "/workspaces/{workspace}",
        "Workspaces",
        "PatchWorkspace",
        "workspaces",
        "WorkspacesAPI",
        "patch",
    ),
]
